Tabzilla pr
naszilla/tabzilla pull request #94
Opened 2023-09-08 17:38 UTC by penfever

Addition of code which allows tabzilla models to run on a subset of data for a given experiment

2023-09-15 21:02 UTC, duncanmcelfresh requested changes
some minor comments, mostly unneeded code. please address these and then I can merge

2023-09-15 21:02 UTC, duncanmcelfresh commented on TabZilla/tabzilla_utils.py
> +    print("Current model: ", model)
if this is for debugging only, please remove

2023-09-15 21:02 UTC, duncanmcelfresh commented on TabZilla/tabzilla_utils.py
> +        print("Done fitting model, history is: ", loss_history, val_loss_history)
this could produce a lot of output, I would rather not include this print statement

2023-09-15 21:02 UTC, duncanmcelfresh commented on TabZilla/tabzilla_utils.py
> +        print("Sample accuracy scores from test set splits: ", scorers["test"].accs)
if this is for debugging alone, please remove

2023-09-19 17:13 UTC, penfever commented on TabZilla/tabzilla_data_processing.py
> +        np.random.seed(seed)
Setting random seed, passed in as an argument

2023-09-19 17:13 UTC, penfever commented on TabZilla/tabzilla_featurizer.py
> +            args=None,
Modifying to match signature

2023-09-21 23:16 UTC, duncanmcelfresh approved these changes

2023-09-21 23:16 UTC, merged